application: mikkolehtinenblog
version: 3
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

builtins:
- remote_api: on
- datastore_admin: on

handlers:

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /admin/static
  static_dir: templates/admin/static/

- url: /static/([^/]+)/(.*)
  static_files: templates/themes/\1/static/\2
  upload: templates/themes/[^/]+/static/.*

- url: /.*
  script: main.py
